blank_issues_enabled: false
contact_links:
  - name: 我的Telegram群组
    url: https://t.me/Spectrollay_MCW
    about: 个人项目聊天群(此处不接受建议和反馈)
  - name: 我的QQ群组
    url: https://qm.qq.com/q/AqLmKLH9mM
    about: 个人项目聊天群(此处不接受建议和反馈)
  - name: 我的云湖群组
    url: https://yhfx.jwznb.com/share?key=VyTE7W7sLwRl&ts=1684642802
    about: 个人项目聊天群(此处不接受建议和反馈)