name: 提出建议
description: 提出你的宝贵想法
title: "[建议]: "
labels: [ "改进" ]

body:
  - type: markdown
    attributes:
      value: |
        ## 感谢你能够向我们提出你的建议!
        ## 以下是一些注意事项,请务必阅读让我们能够更容易处理

        ### 确定没有相同或类似的Issue已被提出.
        ### 确定现有的PR和代码并没有和该建议相同或类似的方法.
        ### 如果你不知道如何有效且精准地表述,我们建议强烈建议你先阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md).

        ---

  - type: checkboxes
    id: terms
    attributes:
      label: 请确保你已阅读以上注意事项,然后勾选下方的确认框.
      options:
        - label: 我确认这个建议是有依据的且有改进意义的.
          required: true
        - label: 我已经在 [Issue Tracker](https://github.com/Spectrollay/minecraft_repository_test/issues) 以及 [Pull Request](https://github.com/Spectrollay/minecraft_repository_test/pulls) 中找过我要提出的建议,没有找到相同或类似的Issue和PR.
          required: true
        - label: 我已知晓并同意,本处仅用于已有内容的建议,否则请在 [这里](https://github.com/Spectrollay/minecraft_repository_test/issues/new/choose) 选择合适的模板.若该Issue是关于其他内容则可能会被无条件自动关闭或/并锁定.
          required: true
        - label: 我已知晓并同意,如果我不按照模板提供的指示进行填写,则该Issue可能会被无条件删除.
          required: true

  - type: input
    id: suggestion-title
    attributes:
      label: 标题
      description: 用一句话简要概述你的建议
    validations:
      required: true

  - type: textarea
    id: current_content
    attributes:
      label: 当前内容
      description: |
        当前的内容在哪里存在问题?
        如果能定位到具体代码位置请一起贴出
    validations:
      required: true

  - type: textarea
    id: suggested_content
    attributes:
      label: 改进意见
      description: |
        你认为怎么修改会更好?
        你提出这个建议的依据是什么?
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: 你的名称
      description: (可选)用于可能的贡献展示
    validations:
      required: false

  - type: input
    id: email
    attributes:
      label: 联系邮箱
      description: (可选)用于可能的贡献展示
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## 感谢你的建议!我们稍后将评估你的提议并向你返回评估结果.
