name: Mirror to Gitea
on: [push, delete, create]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - if: env.GITEA_ACTIONS == 'true'
        run: |
          echo "Detected Gitea Actions, skipping mirror."
          exit 0

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GITEA_SSH_PRIVATE_KEY }}

      - name: Add gitea.com to known_hosts
        run: |
          ssh-keyscan -H gitea.com >> ~/.ssh/known_hosts

      - name: Mirror to Gitea
        run: |
          git remote add gitea git@gitea.com:Spectrollay/mclang_cn.git
          git push --mirror gitea