name: Mirror to Gitea
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  mirror_to_gitea:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Gitea
        env:
          GITEA_TOKEN : ${{secrets.GITEA_TOKEN}}
        run: |
          REMOTE_URL="https://Spectrollay:${GITEA_TOKEN}@gitea.com/Spectrollay/mclang_cn.git"
          git remote add gitea "$REMOTE_URL"
          git push --mirror gitea